'use client'
import { usePathname } from 'next/navigation'

export default function Head() {
  const pathName = usePathname()
  const TITLE = pathName === '/' ? 'NextOne' : 'NextOne - ' + pathName.replace('/', '')
  
  return (
    <>
      <title>{TITLE}</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </>
  )
}
